### ISSUE TITLE
Issue in file WriteWithSql.java

### ISSUE THREAD

**Issue by rahul1205** [cvitter/Riak-TS-Java-Demo#1]
Hi @cvitter 
Firstly, thank you for taking out time to build this awesome repository to get started with riak-ts. The issue I am facing is with the WriteWithSql.java . I am compiling all of these files manually using independent jars as I don't have time to study maven. During compilation phase, I get an error at line 75: where you called a function getCellStringVal() on an object Utility which is not defined in the file. Can you kindly address this issue and help me out. 

UPDATE-My issue was naive. Solved it, sorry!!

**Comment by cvitter** [comment]
No worries at all. I hope the examples help.
